### ISSUE TITLE
getSvyLookupSelectedRecords should return all records not only the first

### ISSUE THREAD

**Issue by philippr71** [Servoy/svyLookup#12]
In the following codeblock it must return foundset.getSelectedRecords() (otherwise the Methodename and Methodedescription is wrong).

If multiselect is activated, multiple records must been returned!

Thanks and regards
Roland

https://github.com/Servoy/svyLookup/blob/2ae23d5d0402da43f04b08518c07c2c835216b0e/svyLookup/forms/AbstractLookup.js#L510

**Comment by seanthomasdevlin** [comment]
Assigned to support case:
https://github.com/Servoy/svyLookup/issues/12

Subscribe to ticket updates to follow progress.

**Comment by paronne** [comment]
This method is overriden in extended abstract form AbstractLookupMulti. The latter abstract form is used for any implementation allowing multi-select of record/values in Lookup. In simple AbstractLookup should not be possible to select multiple values, therefore i don't see anything wrong with this function.
To note this function is always returning an array of records ( even for single selection ) in order to have a consistent return type for both single and multi selection.
