### ISSUE TITLE
enter to select not working on empty fields

### ISSUE THREAD

**Issue by saleman67** [Servoy/svyLookup#4]
When you enter a field with lookup window, a value is already selected, but enter is not working to close the lookup window and select the value. If you press arrow-down and then enter it is working. This is on version 2.0.1.

I also had a older version that I got from Poalo at servoy world, in that version it is working.

**Comment by paronne** [comment]
Hi Sanneke,

since version 2.0.0 pressing ENTER while the focus is on the search Input Field won't close the lookup but will search the values in table instead.

If that is your preferred user experience, you can customize the default behavior and force the lookup to close at the onEnter by extending the existing lookup templates: https://github.com/Servoy/svyLookup/wiki#lookup-templates
https://github.com/Servoy/svyLookup/wiki/Custom-Templates

Regards,
Paolo

**Comment by saleman67** [comment]
Hi Paolo,

Thank you for this. Sorry that I did not read the documentation.
=-O
Have a good day. Regards,

Sanneke Aleman
Yield Software Development
m: +31642022332
w: www.yieldsd.com
e: sanneke@yieldsd.com

------ Original Message ------
